let txt1 = "Budul";
console.log(txt1.length);
console.log(txt1[1]);
console.log(txt1.charAt(1));
console.log(txt1.charCodeAt(1));
console.log(txt1.at(-1));
let txt3 = "NA PEWNO!";
let txt2 = txt1.concat(" is the best.", txt3);
console.log(txt2);
console.log(txt1 + " is the best." + txt3);
console.log(txt1.indexOf("u"));
console.log(txt1.lastIndexOf("u"));
txt2 = txt1.slice(1);
console.log(txt2);
txt3 = txt1.slice(0, 1);
console.log(txt3);
txt3.toLowerCase();
// txt1 = txt3 + txt2;
txt1 = txt3.concat(txt2);
console.log(txt1);
console.log(txt1.slice(1, -1));
console.log(txt1.substring(1));
console.log(txt1.substr(1, 3));
console.log(txt1.toUpperCase);
txt1 = "        BUdowanlod          ";
console.log(txt1);
console.log(txt1.trim());
console.log("słowo " + txt1 + " koniec");
txt1 = "kukułka kuka sobie";
console.log(txt1.replace("ku", "wa"));
console.log(txt1.replaceall("ku", "we"));
txt1 = "Mińsk Mazowiecki obok warszawy";
let arrTxt1 = txt1.split(" ");
console.log(arrTxt1);
console.log(arrTxt1.length);
arrTxt1 = txt1.split("");
console.log(arrTxt1);
console.log(txt1.endsWith("awy"));
console.log(txt1.includes("a"));
txt1 = "Siema ";
txt2 = txt1.repeat(5);
console.log(txt2);
let tel = "500245631";
tel = tel.padStart(12, "+48");
console.log(tel);
